name: "Testing code"
description: "Performs tests on code using pytest."

inputs:
  python_version:
    description: "Python version to test with"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python_version }}

    # POETRY INSTALLATION
    - uses: snok/install-poetry@v1
      with:
        version: 1.1.13
        virtualenvs-create: true
        virtualenvs-in-project: true
    - uses: actions/cache@v2.1.3
      id: cached-poetry-dependencies
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ inputs.python_version }}-${{ hashFiles('**/poetry.lock') }}
    - name: poetry install
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      shell: bash
      run: |
        poetry config experimental.new-installer false
        poetry install --no-interaction --no-root -vvv

    # RUNNING TESTS
    - name: perform tests
      shell: bash
      run: |
        source .venv/bin/activate
        pytest -vvv --cov-report xml --cov=./
