#Updates the Changelog file
#Publishes the package to PyPI on a succesfully merged pull-request to the main branch
name: Changelog + Publishing
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  update-changelog:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: python scripts/update_changelog.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated commit of updated CHANGELOG.md
          branch: main

  publish:
    if: github.event.pull_request.merged == true
    needs: [update-changelog]
    name: Publish to PyPi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/composite/publishing
        with:
          pypi_username: ${{ secrets.PyPI_USERNAME }}
          pypi_password: ${{ secrets.PyPI_PASSWORD }}