name: "Create Visualizations"
description: "Creates visualizations to show in the README file and saves them in the image directory"


runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # POETRY INSTALLATION
    - uses: snok/install-poetry@v1
      with:
        version: 1.1.10
        virtualenvs-create: true
        virtualenvs-in-project: true
    - uses: actions/cache@v2.1.3
      id: cached-poetry-dependencies
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ inputs.python_version }}-${{ hashFiles('**/poetry.lock') }}
    - name: poetry install
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      shell: bash
      run: |
        poetry config experimental.new-installer false
        poetry install --no-interaction -vvv

    - name: run visualization script
      shell: bash
      run: |
        source .venv/bin/activate
        python ${{ github.action_path }}/create_visualizations.py

    - name: git pull
      shell: bash
      run: git pull
    - name: push changes back to branch
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "docs(visualizations): Automated update of visualizations used in README"