name: "Linting code"
description: "Reformats code with black, pushes back any changes, perform linting check with flake8"

runs:
  using: "composite"
  steps:
    # Reformat
    - name: black
      uses: psf/black@stable
    - name: push changes back to branch
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "style(black): Automated reformatting done by black"
        
    # Perform checks
    - uses: actions/setup-python@v2
    - name: flake8
      uses: py-actions/flake8@v1