name: "Linting code"
description: "Reformats code with black, pushes back any changes, perform linting check with flake8"

runs:
  using: "composite"
  steps:
    - uses: psf/black@stable
    - name: push changes back to branch
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "style(black): Automated reformatting done by black"

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: flake8 Lint
      uses: py-actions/flake8@v1