name: 'Testing'
on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: 'Testing'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      # setup poetry and caching
      - uses: snok/install-poetry@v1
        with:
          version: 1.1.10
          virtualenvs-create: true
          virtualenvs-in-project: true
      - uses: actions/cache@v2.1.3
        with:
          path: ~/.cache
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - run: poetry install --no-interaction --no-root -vvv

      #Run tests
      - run: |
          source $VENV
          pytest -vvv --cov-report xml --cov=./
      - name: 'Upload coverage to Codecov'
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
          fail_ci_if_error: true

