name: 'Testing'
on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: 'Testing'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install Python dependencies
        run: |
          python -m pip install --no-cache-dir --upgrade pip
          pip install pytest coverage poetry

      - name: Install Poetry dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --no-root

      - name: Test with tox
        run: |
          pip install tox
          tox -- --cov dufte --cov-report xml --cov-report term

      - name: 'Upload coverage to Codecov'
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

