name: 'Testing'
on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: 'Testing'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: snok/install-poetry@v1
      - run: |
          poetry install --no-root -n
          poetry run coverage run -m pytest 
          poetry run coverage xml
          
      - name: 'Upload coverage to Codecov'
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

