name: 'Testing'
on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: 'Testing'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install Python dependencies
        run: |
          python -m pip install --no-cache-dir --upgrade pip
          pip install poetry

      - name: Install Poetry dependencies
        run: poetry install

      - name: 'Run pytest with coverage'
        run: |
          poetry shell
          coverage run -m pytest 
          coverage xml

      - name: 'Upload coverage to Codecov'
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

