name: 'Testing'
on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: 'Testing'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: false
      - run: |
          poetry install --no-root -n
          coverage run -m pytest 
          coverage xml
          
      - name: 'Upload coverage to Codecov'
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

