#Publishes the package to PyPI on a succesfully merged pull-request to the main branch
name: 'Publishing'
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  publish:
    if: github.event.pull_request.merged == true
    name: Publish to PyPi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      # setup poetry and caching
      - uses: snok/install-poetry@v1
        with:
          version: 1.1.10
          virtualenvs-create: true
          virtualenvs-in-project: true
      - uses: actions/cache@v2.1.3
        with:
          path: ~/.cache
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - run: poetry install --no-interaction --no-root -vvv --no-dev
      - run: poetry build 

      # Publish to PyPI
      - name: Publish package
        env:
          USERNAME: ${{ secrets.PyPI_USERNAME }}
          PASSWORD: ${{ secrets.PyPI_PASSWORD }}
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry publish -r testpypi -u  $USERNAME -p $PASSWORD