name: Push Workflow
on:
  push:
    branches:
      - '**'

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/composite/linting
  
  testing:
    needs: linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7.1", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/composite/testing
        with:
          python_version: ${{ matrix.python-version }}
